#!/usr/bin/env bash
# Generate a self-contained AGENTS.md from the modular CLAUDE.md + rules/.
# Claude inlines the rules/ links; Codex (~/.codex/AGENTS.md) and Copilot CLI
# (~/.copilot/instructions/*.instructions.md) load a single file verbatim and do
# NOT follow markdown links — so the rule bodies must be inlined here. Re-run
# after editing CLAUDE.md or rules/.
set -euo pipefail

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
out="$dir/AGENTS.md"

{
  echo "<!-- GENERATED by build-agents.sh from CLAUDE.md + rules/. Do not edit by hand. -->"
  echo
  # CLAUDE.md verbatim, but flatten the rules/ index links to bold labels since
  # the link targets don't sit next to this flattened file.
  sed -E 's#- \[([^]]+)\]\(rules/[^)]+\) #- **\1** #g' "$dir/CLAUDE.md"
  for f in repos git-github coding; do
    printf '\n---\n\n'
    cat "$dir/rules/$f.md"
  done
} >"$out"

echo "Wrote $out"
