tap "automaat/tap"
tap "automaat/whisper-hotkey"
tap "kong/agent-auth-cli"
tap "shivammathur/php"
tap "smykla-skalski/tap"

brew "antidote"
brew "git"
brew "git-lfs"
brew "mise"
brew "vim"

brew "gnupg"
brew "pinentry-mac"

brew "autoconf"
brew "autojump"
brew "coreutils"
brew "diffutils"
brew "docker-credential-helper"
brew "ffmpeg"
brew "oniguruma"
brew "ponysay"
brew "postgresql@14"
brew "pyenv"
brew "rbenv"
brew "rsync"
brew "rustup"
brew "tmux"
brew "tree"

brew "automaat/tap/cache-buster"
brew "kong/agent-auth-cli/agent-auth-cli"
brew "rtk"
brew "smykla-skalski/tap/klaudiush"

cask "1password"
cask "1password-cli"
cask "airbuddy"
cask "bitwarden"
cask "codex"
cask "contexts"
cask "disk-inventory-x"
cask "freedom"
cask "hammerspoon"
cask "logi-options+"
cask "microsoft-edge"
cask "notion"
cask "obsidian"
cask "raycast"
cask "todoist-app"
cask "zed"

cask "bambu-studio"
cask "freecad"
cask "openscad"

cask "balenaetcher"
cask "copilot-cli"
cask "gcloud-cli"
cask "ghostty"
cask "insomnia"
cask "jetbrains-toolbox"
cask "orbstack"
cask "pgadmin4"
cask "visual-studio-code"

cask "vivaldi"
cask "google-drive"
cask "discord"
cask "signal"

cask "home-assistant"
cask "tailscale-app"
cask "wch-ch34x-usb-serial-driver"

cask "adobe-acrobat-reader"
cask "elgato-stream-deck"
cask "xnviewmp"

cask "font-fira-code-nerd-font"
cask "font-iosevka"
cask "font-iosevka-nerd-font"
cask "font-iosevka-term-nerd-font"
cask "font-symbols-only-nerd-font"

cask "basictex"
