export EDITOR=vim
export GOPRIVATE="github.com/Kong/*"
export MISE_AUTO_INSTALL=1
export XDG_CONFIG_HOME="$HOME/.config"
export ZAKWAS_CONFIG="$HOME/sideprojects/environment-as-code/zakwas.yaml"

[[ ! -r ~/.config/zsh/secrets.zsh ]] || source ~/.config/zsh/secrets.zsh
